[2023-07-10 14:18:11,037] ERROR log_exception() L1449 Exception on /paciente [GET] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py", line 93, in get_paciente
    paciente_id = query.id
AttributeError: 'PacienteBuscaSchema' object has no attribute 'id'
[2023-07-10 14:18:11,038] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:18:11] "[35m[1mGET /paciente?nome=ana HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:18:11,615] ERROR log_exception() L1449 Exception on /paciente [GET] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py", line 93, in get_paciente
    paciente_id = query.id
AttributeError: 'PacienteBuscaSchema' object has no attribute 'id'
[2023-07-10 14:18:11,616] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:18:11] "[35m[1mGET /paciente?nome=ana HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:55,253] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.2.15:5000 (Press CTRL+C to quit) - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:55,254] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:58,625] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:19:58] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:58,743] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:19:58] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:58,880] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:19:58] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:58,887] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:19:58] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:19:58,891] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:19:58] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:07,421] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:20:07,441] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:20:07] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:10,501] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:10] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:10,544] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:10] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:10,556] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:10] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:10,559] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:10] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:10,918] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:10] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:26,345] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Marcos Filipi' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:20:26,358] DEBUG add_paciente() L48   Adicionado paciente de nome: 'Marcos Filipi' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L48  
[2023-07-10 14:20:26,360] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:26] "POST /paciente HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:32,046] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Marcos Filipi' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:20:32,047] WARNING add_paciente() L54   Erro ao adicionar paciente 'Marcos Filipi', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:20:32,048] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:20:32] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:20:39,299] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:20:39,301] DEBUG get_pacientes() L81   1 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 14:20:39,301] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:20:39] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:21:00,272] DEBUG add_paciente() L40   Adicionando paciente de nome: 'Ana' - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L40  
[2023-07-10 14:21:00,273] WARNING add_paciente() L54   Erro ao adicionar paciente 'Ana', Paciente de mesmo nome j√° salvo na base :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L54  
[2023-07-10 14:21:00,273] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:21:00] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:21:03,023] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
[2023-07-10 14:21:03,025] DEBUG get_pacientes() L81   1 pacientes econtrados - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L81  
[2023-07-10 14:21:03,025] INFO _log() L224  127.0.0.1 - - [10/Jul/2023 14:21:03] "GET /pacientes HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:21:41,672] DEBUG get_pacientes() L71   Coletando dados dos pacientes  - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L71  
