[2023-07-10 14:27:51,444] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:27:51] "[35m[1mGET /paciente?nome=Marcos%20Filipi HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 14:27:59,996] ERROR log_exception() L1449 Exception on /paciente [GET] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py", line 93, in get_paciente
    paciente_id = query.id
AttributeError: 'PacienteBuscaSchema' object has no attribute 'id'
[2023-07-10 14:27:59,997] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 14:27:59] "[35m[1mGET /paciente?nome=2 HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:00:27,765] DEBUG add_comentario() L145  Adicionando coment√°rios ao paciente #2 - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L145 
[2023-07-10 15:00:27,805] DEBUG add_comentario() L165  Adicionado coment√°rio ao paciente #2 - call_trace=/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/app.py L165 
[2023-07-10 15:00:27,820] INFO _log() L224  10.0.2.15 - - [10/Jul/2023 15:00:27] "POST /cometario HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-07-10 15:00:54,832] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP/projeto API/meu_app_back/schemas/paciente.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
